// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sparrow.proto at 18:1
package edu.berkeley.cs194;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * Control message sent between the client and server before data exchange.
 */
public final class Handshake extends Message<Handshake, Handshake.Builder> {
  public static final ProtoAdapter<Handshake> ADAPTER = new ProtoAdapter_Handshake();

  private static final long serialVersionUID = 0L;

  /**
   * A list of features that the sender of the message supports.
   */
  @WireField(
      tag = 1,
      adapter = "edu.berkeley.cs194.Feature#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Feature> features;

  public Handshake(List<Feature> features) {
    this(features, ByteString.EMPTY);
  }

  public Handshake(List<Feature> features, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.features = Internal.immutableCopyOf("features", features);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.features = Internal.copyOf("features", features);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Handshake)) return false;
    Handshake o = (Handshake) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(features, o.features);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (features != null ? features.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (features != null) builder.append(", features=").append(features);
    return builder.replace(0, 2, "Handshake{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Handshake, Builder> {
    public List<Feature> features;

    public Builder() {
      features = Internal.newMutableList();
    }

    /**
     * A list of features that the sender of the message supports.
     */
    public Builder features(List<Feature> features) {
      Internal.checkElementsNotNull(features);
      this.features = features;
      return this;
    }

    @Override
    public Handshake build() {
      return new Handshake(features, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Handshake extends ProtoAdapter<Handshake> {
    ProtoAdapter_Handshake() {
      super(FieldEncoding.LENGTH_DELIMITED, Handshake.class);
    }

    @Override
    public int encodedSize(Handshake value) {
      return Feature.ADAPTER.asRepeated().encodedSizeWithTag(1, value.features)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Handshake value) throws IOException {
      if (value.features != null) Feature.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.features);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Handshake decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: {
            try {
              builder.features.add(Feature.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Handshake redact(Handshake value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
